### ISSUE TITLE
Error: no instance of function template "alignLengthBackward::operator()

### ISSUE THREAD

**Issue by euduca** [masayano/CLAST#3]
**Hi, folks.**

GCC: 5.3.0
CUDA: 7.5
GPU: Nvidia Tesla K20
# Location of the CUDA Toolkit:

CUDA_PATH ?= "/opt/cuda/7.5"

CUDA code generation flags:
GENCODE_FLAGS   := $(GENCODE_SM35)

[clast-error.txt](https://github.com/masayano/CLAST/files/114455/clast-error.txt)
The entire output is in the attached file.

How can I resolve this error?

```
/opt/cuda/7.5/bin/..//include/thrust/detail/function.h(96): error: no instance of function template "alignLengthBackward::operator()" matches the argument list
            argument types are: (thrust::tuple<int, int, int, int, int, int, int, int, int, thrust::null_type>, thrust::detail::tuple_of_iterator_references<int &, int &, int &, int &, int &, int &, int &, int &, int &, thrust::null_type>)
            object type is: alignLengthBackward
          detected during:
            instantiation of "Result thrust::detail::wrapped_function<Function, Result>::operator()(Argument1 &, const Argument2 &) const [with Function=alignLengthBackward, Result=__nv_bool, Argument1=thrust::tuple<int, int, int, int, int, int, int, int, int, thrust::null_type>, Argument2=thrust::detail::tuple_of_iterator_references<thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::device_reference<int>, thrust::null_type>]" 
```

**Comment by masayano** [comment]
Hi euduca,

Thank you for your report.
Would you please let me know the version of thrust library?
Some version of thrust library does not match for CLAST.

> 0 Dependenies.
> 1 CUDA (version 4.0~)
> 2 "boost library"
> 3 "thrust library (version ~1.7)" <- very important
> 4 NVIDIA GPU (newer than Fermi architecture)

masayano

**Comment by euduca** [comment]
Hi @Masayano.
Thanks for help me.
I found this in the CUDA documentation folder.

> Installing the CUDA Toolkit will copy Thrust header files to the standard CUDA include directory for your system. Since Thrust is a template library of header files, no further installation is necessary to start using Thrust.
> 
> In addition, new versions of Thrust continue to be available online through the GitHub Thrust project page. **The version of Thrust included in this version of the CUDA Toolkit corresponds to version 1.7.0 from the Thrust project page.**
> - See more at: file:///tmp/thrust/index.html#sthash.znqVzPjj.dpuf

I downloaded the thrust 1.8.1 from https://thrust.github.io/ and replaced the thrust library. I moved the original thurst folder elsewhere.

> Simply download the newest version from the Downloads section and extract the contents of the zip file to a directory. We suggest installing Thrust to the CUDA include directory, which is usually /usr/local/cuda/include/ on a Linux and Mac OSX.

But,  I got the same error =/
[error_with_thrust_1.8.1_cuda_7.5_gcc_5.3.0.txt](https://github.com/masayano/CLAST/files/115732/error_with_thrust_1.8.1_cuda_7.5_gcc_5.3.0.txt

Thanks.

**Comment by euduca** [comment]
Sorry, I closed unintentionally.

Duca.

**Comment by masayano** [comment]
Hi euduca,

Thank you for your checking.

But it's strange, because today I tried to install CUDA 7.5 to a new environment (test environment), checked the thrust version again, and found that the version is "1.8.2". It means that CUDA 7.5 has thrust version "1.8.2" as defaults. I think that it's mistake of "CUDA documentation folder".

You can check the real thrust version by seeing "#define THRUST_VERSION" of "[Your thrust directory path]/version.h". [Your thrust directory path] is usually "/usr/local/cuda/include/thrust" as you said.

Please make sure that the thrust version is "1.7.0" (or former, for example "1.6.0"), and build again. I also failed to build when I used thrust version "1.8.2", and I could successfully build when I used thrust version "1.7.0" in test environment.

Sorry for inconvenience.

masayano

**Comment by euduca** [comment]
Hi, @masayano 
I believe there is no reason to apologize. This type of information exchange can help other users clast. =)
I who should thank you for the attention you are having with my problem.
I check the thrust of the information that came with CUDA, and found this:
#define THRUST_VERSION 100802
So I downloaded the thrust 1.7, and checked the version in version.h file:
#define THRUST_VERSION 100700
I used version 1.7 and compilation work properly.
I believe that the CUDA documentation about the library could make me believe that I was using the correct version.
Thank you so much.
